[project]
name = "right-word-eeg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mne>=1.9.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "synapseclient>=4.7.0",
]
